name: Continuous Integration
on:
  push:
    branches: [ "feature/next-gen" ]
  pull_request:
    branches: [ "feature/next-gen" ]

jobs:
  # build:
  #   runs-on: macos-14
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Build
  #       run: ./Tools/build_frameworks.sh
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v4.4.1
  check_links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          fail: true
